#!/bin/bash

export DBAPI_API_CONTEXT=${API_CONTEXT:-"api"}

export SPRING_DATASOURCE_URL=${DB_URL}
export SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
export SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
export SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DB_DRIVER:-"com.mysql.cj.jdbc.driver"}

export SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_ADDRESS}
export SPRING_CLOUD_NACOS_DISCOVERY_USERNAME=${NACOS_USERNAME}
export SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD=${NACOS_PASSWORD}
export SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=${NACOS_NAMESPACE}